/*
 * Created on 2024-04-08 ( 22:27:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.common.sec.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * JPA entity class for "ArClients"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="ar_clients" )
public class ArClients implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="client_id", nullable=false, length=50)
    private String     clientId ;

    @Column(name="ar_id", nullable=false)
    private Integer    arId ;

    @Column(name="created_by")
    @JsonManagedReference
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    @JsonManagedReference
    private Date       createdOn ;

    @Column(name="modified_by")
    @JsonManagedReference
    private Integer    modifiedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    @JsonManagedReference
    private Date       modifiedOn ;

    @Column(name="active_c", length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    @JsonManagedReference
    private UserReg    userReg2 ; 

    @ManyToOne
    @JoinColumn(name="ar_id", referencedColumnName="id", insertable=false, updatable=false)
    @JsonManagedReference
    private UserReg    userReg ; 

    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    @JsonManagedReference
    private UserReg    userReg3 ; 


    /**
     * Constructor
     */
    public ArClients() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setClientId( String clientId ) {
        this.clientId = clientId ;
    }
    public String getClientId() {
        return this.clientId;
    }

    public void setArId( Integer arId ) {
        this.arId = arId ;
    }
    public Integer getArId() {
        return this.arId;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public UserReg getUserReg2() {
        return this.userReg2;
    } 

    public UserReg getUserReg() {
        return this.userReg;
    } 

    public UserReg getUserReg3() {
        return this.userReg3;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(clientId);
        sb.append("|");
        sb.append(arId);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
