/*
 * Created on 2024-04-08 ( 22:27:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.common.sec.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "ArProfile"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="ar_profile")
public class ArProfile implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=50)
    private String     name ;

    @Temporal(TemporalType.DATE)
    @Column(name="dob", nullable=false)
    private Date       dob ;

    @Column(name="fname", nullable=false, length=50)
    private String     fname ;

    @Column(name="address", nullable=false, length=100)
    private String     address ;

    @Column(name="dist", nullable=false)
    private Integer    dist ;

    @Column(name="state", nullable=false)
    private Integer    state ;

    @Column(name="country", nullable=false)
    private Integer    country ;

    @Column(name="create_by")
    private Integer    createBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;

    @Column(name="ar_id")
    private Integer    arId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="ar_id", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg ; 

    @ManyToOne
    @JoinColumn(name="create_by", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg2 ; 

    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg3 ; 


    /**
     * Constructor
     */
    public ArProfile() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDob( Date dob ) {
        this.dob = dob ;
    }
    public Date getDob() {
        return this.dob;
    }

    public void setFname( String fname ) {
        this.fname = fname ;
    }
    public String getFname() {
        return this.fname;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setDist( Integer dist ) {
        this.dist = dist ;
    }
    public Integer getDist() {
        return this.dist;
    }

    public void setState( Integer state ) {
        this.state = state ;
    }
    public Integer getState() {
        return this.state;
    }

    public void setCountry( Integer country ) {
        this.country = country ;
    }
    public Integer getCountry() {
        return this.country;
    }

    public void setCreateBy( Integer createBy ) {
        this.createBy = createBy ;
    }
    public Integer getCreateBy() {
        return this.createBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    public void setArId( Integer arId ) {
        this.arId = arId ;
    }
    public Integer getArId() {
        return this.arId;
    }

    //--- GETTERS FOR LINKS
    public UserReg getUserReg() {
        return this.userReg;
    } 

    public UserReg getUserReg2() {
        return this.userReg2;
    } 

    public UserReg getUserReg3() {
        return this.userReg3;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(dob);
        sb.append("|");
        sb.append(fname);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(dist);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(country);
        sb.append("|");
        sb.append(createBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(activeC);
        sb.append("|");
        sb.append(arId);
        return sb.toString(); 
    } 

}
