/*
 * Created on 2024-04-08 ( 22:27:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.common.sec.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "PacEntityMstr"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="pac_entity_mstr", schema="public" )
public class PacEntityMstr implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="pac_entity_name", length=100)
    private String     pacEntityName ;

    @Column(name="pac_group_id")
    private Integer    pacGroupId ;

    @Column(name="holding_percent")
    private BigDecimal holdingPercent ;

    @Column(name="record_status", nullable=false, length=1)
    private String     recordStatus ;

    @Column(name="created_by")
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="active_c", length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="pac_group_id", referencedColumnName="id", insertable=false, updatable=false)
    private PacGroupMstr pacGroupMstr ; 

    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg2 ; 

    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg ; 


    /**
     * Constructor
     */
    public PacEntityMstr() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setPacEntityName( String pacEntityName ) {
        this.pacEntityName = pacEntityName ;
    }
    public String getPacEntityName() {
        return this.pacEntityName;
    }

    public void setPacGroupId( Integer pacGroupId ) {
        this.pacGroupId = pacGroupId ;
    }
    public Integer getPacGroupId() {
        return this.pacGroupId;
    }

    public void setHoldingPercent( BigDecimal holdingPercent ) {
        this.holdingPercent = holdingPercent ;
    }
    public BigDecimal getHoldingPercent() {
        return this.holdingPercent;
    }

    public void setRecordStatus( String recordStatus ) {
        this.recordStatus = recordStatus ;
    }
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public PacGroupMstr getPacGroupMstr() {
        return this.pacGroupMstr;
    } 

    public UserReg getUserReg2() {
        return this.userReg2;
    } 

    public UserReg getUserReg() {
        return this.userReg;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(pacEntityName);
        sb.append("|");
        sb.append(pacGroupId);
        sb.append("|");
        sb.append(holdingPercent);
        sb.append("|");
        sb.append(recordStatus);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
