/*
 * Created on 2024-04-08 ( 22:27:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.common.sec.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "RefreshToken"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="refresh_token" )
public class RefreshToken implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="refresh_token", nullable=false, length=200)
    private String     refreshToken ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expiry_date", nullable=false)
    private Date       expiryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="created_by")
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;

    @Column(name="user_reg_id")
    private Integer    userRegId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="user_reg_id", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg ; 


    /**
     * Constructor
     */
    public RefreshToken() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setRefreshToken( String refreshToken ) {
        this.refreshToken = refreshToken ;
    }
    public String getRefreshToken() {
        return this.refreshToken;
    }

    public void setExpiryDate( Date expiryDate ) {
        this.expiryDate = expiryDate ;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    public void setUserRegId( Integer userRegId ) {
        this.userRegId = userRegId ;
    }
    public Integer getUserRegId() {
        return this.userRegId;
    }

    //--- GETTERS FOR LINKS
    public UserReg getUserReg() {
        return this.userReg;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(refreshToken);
        sb.append("|");
        sb.append(expiryDate);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        sb.append("|");
        sb.append(userRegId);
        return sb.toString(); 
    } 

}
