/*
 * Created on 2024-04-08 ( 22:27:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.common.sec.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "ShareHoldingLimitPerctge"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="share_holding_limit_perctge", schema="public" )
public class ShareHoldingLimitPerctge implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="holding_base_prctg_lmt")
    private BigDecimal holdingBasePrctgLmt ;

    @Column(name="holding_proposed_prctg_lmt")
    private BigDecimal holdingProposedPrctgLmt ;

    @Column(name="share_holding_cat_id", nullable=false)
    private Integer    shareHoldingCatId ;

    @Column(name="record_status", nullable=false, length=15)
    private String     recordStatus ;

    @Column(name="created_by")
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg2 ; 

    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private UserReg    userReg ; 

    @ManyToOne
    @JoinColumn(name="share_holding_cat_id", referencedColumnName="id", insertable=false, updatable=false)
    private ShareHoldingCatMstr shareHoldingCatMstr ; 


    /**
     * Constructor
     */
    public ShareHoldingLimitPerctge() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setHoldingBasePrctgLmt( BigDecimal holdingBasePrctgLmt ) {
        this.holdingBasePrctgLmt = holdingBasePrctgLmt ;
    }
    public BigDecimal getHoldingBasePrctgLmt() {
        return this.holdingBasePrctgLmt;
    }

    public void setHoldingProposedPrctgLmt( BigDecimal holdingProposedPrctgLmt ) {
        this.holdingProposedPrctgLmt = holdingProposedPrctgLmt ;
    }
    public BigDecimal getHoldingProposedPrctgLmt() {
        return this.holdingProposedPrctgLmt;
    }

    public void setShareHoldingCatId( Integer shareHoldingCatId ) {
        this.shareHoldingCatId = shareHoldingCatId ;
    }
    public Integer getShareHoldingCatId() {
        return this.shareHoldingCatId;
    }

    public void setRecordStatus( String recordStatus ) {
        this.recordStatus = recordStatus ;
    }
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public UserReg getUserReg2() {
        return this.userReg2;
    } 

    public UserReg getUserReg() {
        return this.userReg;
    } 

    public ShareHoldingCatMstr getShareHoldingCatMstr() {
        return this.shareHoldingCatMstr;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(holdingBasePrctgLmt);
        sb.append("|");
        sb.append(holdingProposedPrctgLmt);
        sb.append("|");
        sb.append(shareHoldingCatId);
        sb.append("|");
        sb.append(recordStatus);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
