/*
 * Created on 2024-04-08 ( 22:27:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.common.sec.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * JPA entity class for "UserReg"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "user_reg")
@JsonIgnoreProperties({"listOfRoleMstr","listOfPacEntityMstr","listOfShareHoldingCatMstr",
	                   "userCatMstr","listOfPacGroupMstr","listOfRefreshToken","listOfGroupMstr",
	                   "listOfGroupRole","listOfArClients",
	                   "secrete","createdOn","createdBy","modifiedOn","modifiedBy","activeC"})
public class UserReg implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	private Integer id;

	// --- ENTITY DATA FIELDS
	@Column(name = "loginid", nullable = false, length = 100)
	private String loginid;

	@Column(name = "email", nullable = false, length = 100)
	private String email;

	@Column(name = "pwd", nullable = false, length = 100)
	private String pwd;

	@Column(name = "user_ctg_id", nullable = false)
	private Integer userCtgId;

	@Column(name = "is2f_enabled")
	private Boolean is2fEnabled;

	@Column(name = "secrete", length = 150)
	@JsonManagedReference
	private String secrete;

	@Column(name = "mobile", length = 15)
	private String mobile;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on")
	@JsonManagedReference
	private Date createdOn;

	@Column(name = "created_by")
	@JsonManagedReference
	private Integer createdBy;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on")
	@JsonManagedReference
	private Date modifiedOn;

	@Column(name = "modified_by")
	@JsonManagedReference
	private Integer modifiedBy;

	@Column(name = "active_c", nullable = false, length = 1)
	private String activeC;

	// --- ENTITY LINKS ( RELATIONSHIP )

	@ManyToOne
	@JoinColumn(name = "created_by", referencedColumnName = "id", insertable = false, updatable = false)
	@JsonManagedReference
	private UserReg createdByUser;
	
	@ManyToOne
	@JoinColumn(name = "modified_by", referencedColumnName = "id", insertable = false, updatable = false)
	@JsonManagedReference
	private UserReg modifiedByUser;
	
	@ManyToOne
	@JoinColumn(name = "user_ctg_id", referencedColumnName = "id", insertable = false, updatable = false)
	@JsonManagedReference
	private UserCatMstr userCatMstr;

	/**
	 * Constructor
	 */
	public UserReg() {
		super();
	}

	// --- GETTERS & SETTERS FOR FIELDS
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	public String getLoginid() {
		return this.loginid;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return this.email;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setUserCtgId(Integer userCtgId) {
		this.userCtgId = userCtgId;
	}

	public Integer getUserCtgId() {
		return this.userCtgId;
	}

	public void setIs2fEnabled(Boolean is2fEnabled) {
		this.is2fEnabled = is2fEnabled;
	}

	public Boolean getIs2fEnabled() {
		return this.is2fEnabled;
	}

	public void setSecrete(String secrete) {
		this.secrete = secrete;
	}

	public String getSecrete() {
		return this.secrete;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setActiveC(String activeC) {
		this.activeC = activeC;
	}

	public String getActiveC() {
		return this.activeC;
	}

	// --- GETTERS FOR LINKS

	public UserReg getCreatedByUser() {
		return this.createdByUser;
	}


	public UserReg getModifiedByUser() {
		return this.modifiedByUser;
	}

	

	public UserCatMstr getUserCatMstr() {
		return this.userCatMstr;
	}

	

	// --- toString specific method
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(id);
		sb.append("|");
		sb.append(loginid);
		sb.append("|");
		sb.append(email);
		sb.append("|");
		sb.append(pwd);
		sb.append("|");
		sb.append(userCtgId);
		sb.append("|");
		sb.append(is2fEnabled);
		sb.append("|");
		sb.append(secrete);
		sb.append("|");
		sb.append(mobile);
		sb.append("|");
		sb.append(createdOn);
		sb.append("|");
		sb.append(createdBy);
		sb.append("|");
		sb.append(modifiedOn);
		sb.append("|");
		sb.append(modifiedBy);
		sb.append("|");
		sb.append(activeC);
		return sb.toString();
	}

}
