/*
 * Created on 2024-04-08 ( 23:25:15 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.common.sec.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * JPA entity class for "UserCatGroup"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="user_cat_group" )
@JsonIgnoreProperties({"modifiedByUser","createdByUser","userCatMstr", "groupMstr", 
	                   "createdOn","createdBy","modifiedOn","modifiedBy","activeC"})
public class UserCatGroup implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="user_cat_id", nullable=false)
    private Integer    userCatId ;

    @Column(name="group_id", nullable=false)
    private Integer    groupId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", nullable=false)
    private Date       createdOn ;

    @Column(name="created_by")
    @JsonManagedReference
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    @JsonManagedReference
    private Date       modifiedOn ;

    @Column(name="modified_by")
    @JsonManagedReference
    private Integer    modifiedBy ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="modified_by", referencedColumnName="id", insertable=false, updatable=false)
    @JsonManagedReference
    private UserReg    modifiedByUser ; 

    @ManyToOne
    @JoinColumn(name="group_id", referencedColumnName="id", insertable=false, updatable=false)
    @JsonManagedReference
    private GroupMstr  groupMstr ; 

    @ManyToOne
    @JoinColumn(name="user_cat_id", referencedColumnName="id", insertable=false, updatable=false)
    @JsonManagedReference
    private UserCatMstr userCatMstr ; 

    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    @JsonManagedReference
    private UserReg    createdByUser ; 


    /**
     * Constructor
     */
    public UserCatGroup() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setUserCatId( Integer userCatId ) {
        this.userCatId = userCatId ;
    }
    public Integer getUserCatId() {
        return this.userCatId;
    }

    public void setGroupId( Integer groupId ) {
        this.groupId = groupId ;
    }
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public UserReg getModifiedByUser() {
        return this.modifiedByUser;
    } 

    public GroupMstr getGroupMstr() {
        return this.groupMstr;
    } 

    public UserCatMstr getUserCatMstr() {
        return this.userCatMstr;
    } 

    public UserReg getCreatedByUser() {
        return this.createdByUser;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(userCatId);
        sb.append("|");
        sb.append(groupId);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
