package com.nseit.shareholder1.ENUM;

public enum StatusCode {
	
	STAGE_ONE_SUBMISSION_PENDING("STAGE_ONE_SUBMISSION_PENDING"),
	STAGE_ONE_VERIFICATION_PENDING("STAGE_ONE_VERIFICATION_PENDING"),
	STAGE_ONE_DOCUMENT_DEFICIENCY("STAGE_ONE_DOCUMENT_DEFICIENCY"),
	STAGE_TWO_SUBMISSION_PENDING("STAGE_TWO_SUBMISSION_PENDING"),
	STAGE_TWO_VERIFICATION_PENDING("STAGE_TWO_VERIFICATION_PENDING"),
	STAGE_TWO_DOCUMENT_DEFICIENCY("STAGE_TWO_DOCUMENT_DEFICIENCY"),
	VERIFIED("VERIFIED"),
    TRANSFER_PENDING_FROM_DEPOSITORY("TRANSFER_PENDING_FROM_DEPOSITORY"),
	SHARE_TRANSFER_COMPLETED("SHARE_TRANSFER_COMPLETED"),
	STAGE_ONE_VERIFIED("STAGE_ONE_VERIFIED"),
	IN_PRINCIPAL_PENDING("IN_PRINCIPAL_PENDING"),
	REJECTED("REJECTED");
    
	private String msg;
	StatusCode(String msg) {
		this.msg = msg;
	}
	
	public String getMsg() {
		return msg;
	}
	public void setMsg(String msg) {
		this.msg = msg;
	}

	

}
