package com.nseit.shareholder1.web.rest.errors;

public enum EnumResponseCode {
	SUCCESS("701","Success"),
	ERROR("802","General Error"),	
	INTERNAL_SERVER_ERROR("500","Internal Server Error"),
	BAD_REQUEST("400","Bad Request"),
	UNAUTHORIZED("401","Unauthorized"),
	NOT_FOUND("404","Not Found"),
	CONFLICT("409","Conflict"),
	INVALID_CREDENTIAL("405","INVALID_CREDENTIAL"),
	FORBIDDEN("403","FORBIDDEN"),
	NO_DATA("204","NO_DATA"),
	ALREADY_USER_EXIST("410","ALREADY_USER_EXIST"),
	PHONE_EMAIL_INCORRECT("411","PHONE_EMAIL_INCORRECT"),
	INVALID_CLIENT_ID("412","INVALID_CLIENT_ID"),
	OTP_VERIFICATION_FAILED("413","OTP_VERIFICATION_FAILED"),
	INVALID_ANSWER("414","INVALID_ANSWER"),
	OTP_VERIFICATION_TIMEOUT("415","OTP_VERIFICATION_TIMEOUT"),
	SECURITY_VERIFICATION_TIMEOUT("416","SECURITY_VERIFICATION_TIMEOUT"),
	INVALID_BROKER_DETAILS("417","INVALID_BROKER_DETAILS"),
	BROKER_ALREADY_EXIST("418","BROKER_ALREADY_EXIST"),
	INVALID_LOGIN_OTP("419","INVALID_LOGIN_OTP"),
		LOGIN_OTP_TIMEOUT("420","LOGIN_OTP_TIMEOUT"),
	FILE_NOT_SELECTED("421","FILE_NOT_SELECTED"),
	INCORRECT_UUID("422","INCORRECT_UUID"),
	METADATA_VERSION_EXIST("423","METADATA_VERSION_EXIST"),
	INVALID_PASSWORD("424","INVALID_PASSWORD"),
	OLD_NEW_PASSWORD_SAME("425","OLD_NEW_PASSWORD_SAME"),
	NEW_CONFIRM_PASSWORD_MISMATCH("426","NEW_CONFIRM_PASSWORD_MISMATCH"),
	PASSWORD_IS_NULL("427","PASSWORD_IS_NULL"),
	INVALID_USER_ID("428","INVALID_USER_ID"),
	UPDATE_PASSWORD("429","UPDATE_PASSWORD"),
	USER_NOT_EXIST("430","USER_NOT_EXIST"),
	OTP_NOT_VERIFIED("431","OTP_NOT_VERIFIED"),
	IDAM_USER_NOT_CREATED("432","IDAM_USER_NOT_CREATED"),
	VALIDATION_ERROR("433","VALIDATION_ERROR"),
	DOWNLOAD_FAIL("434","DOWNLOAD_FAIL"),
	INVALID_STATUS_CODE("435","INVALID_STATUS_CODE"),
	ROLENAME_ALREADY_EXISTS("436","ROLENAME_ALREADY_EXISTS"),
	SHAREHOLDING_LIMIT_UNAVAILABLE("437","SHAREHOLDING_LIMIT_UNAVAILABLE"),
	GROUP_NOT_EXIST("438","GROUP_NOT_EXIST"),
	ENTITY_NOT_ALLOWED("439","ENTITY_NOT_ALLOWED"),
	ALREADY_ENTITY_EXIST("440","ALREADY_ENTITY_EXIST"),
	PROPOSED_CHANGE_EXIST("441","PROPOSED_CHANGE_EXIST"),
	INCORRECT_FILE_SELECTED("442","INCORRECT_FILE_SELECTED"),
	INVALID_ROLE("443","INVALID_ROLE"),
	INVALID_FILE("444","INVALID_FILE"),
	WORKFLOW_NOT_ALLOWED("445","WORKFLOW_NOT_ALLOWED"),
	INVALID_UUID("446","INVALID_UUID"),
	SAME_USER("447","SAME_USER"),
	INSUFFICIENT_SHARES("448","INSUFFICIENT_SHARES"),
	INVALID_MODE_OF_TRANSFER("449","INVALID_MODE_OF_TRANSFER"),
	FILE_NOT_FOUND("450","FILE_NOT_FOUND");
	
	private String code;
	private String msg;
	private EnumResponseCode(String code, String msg) {
		this.code = code;
		this.msg = msg;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getMsg() {
		return msg;
	}
	public void setMsg(String msg) {
		this.msg = msg;
	}
}
